### ISSUE TITLE
New business rules

### ISSUE THREAD

**Issue by pmaldonado-espol** [Razyelito/ISII_WORKSHOPS_BROKER#1] opened 2023-01-19 12:41 UTC
Dear support team, we are satisfied about your hard work during this last year. On this new year we want to be bigger and better. In the meeting with the Accounting Department and Business Intelligent Group, we proposed some changes with the intention of improving our service and getting more customers. The new business rule establishes: If the customer is married and has more than 30 years old but younger than 60, then $50 must be decreased to the base premium for each one, however if the customer is single, woman and older than 60 years old , she will receive a discount for around $50.

You need to know that all rules should be maintained how it was coming. Our request should be added to the existing one and the result should be calculated with all rules applied.

**Comment by densreye** [comment] 2023-01-20 03:44
I will be in charge of the issues reported

**Comment by densreye** [comment] 2023-01-20 04:11
The changes in the code:
DESCUENTONUEVO=50

if ((getEdad() > 30) && (getEdad() < 60) && (getEstado().equals("Casado"))) {
          premium -= DESCUENTONUEVO;
        }
      if ((getEdad() > 60) && (getEdad() < 80) && (getEstado().equals("No Casado")) && (getSexo().equals("F"))) {
          premium -= DESCUENTONUEVO;
        }

https://github.com/densreye/ISII_WORKSHOPS_BROKER/blob/IssueManagement/ec.edu.espol.workshops/lib/src/main/java/lib/CarInsurance.java#:~:text=%7D-,if%20((getEdad()%20%3E%2030)%20%26%26%20(getEdad()%20%3C%2060)%20%26%26%20(getEstado,%7D,-%7D

**Comment by densreye** [comment] 2023-01-20 04:13
Test:

Sistema de Insurance
///////////////////////////////
Ingresar edad del cliente:
62
Ingresar sexo del cliente(M o F):
F
El cliente es casado?(Y o N):
N
El cliente entrego licencia valida?(Y o N): Y
250
---------------------------------------------------------

Sistema de Insurance
///////////////////////////////
Ingresar edad del cliente:
35
Ingresar sexo del cliente(M o F):
M
El cliente es casado?(Y o N):
Y
El cliente entrego licencia valida?(Y o N): Y
350

**Comment by densreye** [comment] 2023-01-20 04:19
We request your review of the solution @pmaldonado-espol

**Comment by densreye** [comment] 2023-01-20 04:24
@pmaldonado-espol 
To run the enhancements:
1. You need to download the issuesManagement branch
2. Run the Car Insurance file
3. The fields to test are 30<age <60 "Married" status or 60<age <80 "Not Married" status

**Comment by pmaldonado-espol** [comment] 2023-01-20 13:01
> @pmaldonado-espol To run the enhancements:
> 
> 1. You need to download the issuesManagement branch
> 2. Run the Car Insurance file
> 3. The fields to test are 30<age <60 "Married" status or 60<age <80 "Not Married" status

I need a user manual with the instructions to run the application.

**Comment by densreye** [comment] 2023-01-20 14:35
@pmaldonado-espol 

Run the file CarInsurance
1. Clic right and select run CarInsurance
2.  Then put age in the app
3. Then put M or F if a male or female
4. Then put state Y or N if married or not married
5. Then put Y or N if have id for drive
6. See the results in the app

**Comment by densreye** [comment] 2023-01-20 15:55
@pmaldonado-espol attached the file with
[UserManual_CarInsurance.docx](https://github.com/densreye/ISII_WORKSHOPS_BROKER/files/10467866/UserManual_CarInsurance.docx)
 the instructions

**Comment by densreye** [comment] 2023-01-20 17:14
@pmaldonado-espol , I'm waiting for your reply

**Comment by pmaldonado-espol** [comment] 2023-01-20 17:22
> @pmaldonado-espol attached the file with
> [UserManual_CarInsurance.docx](https://github.com/densreye/ISII_WORKSHOPS_BROKER/files/10467866/UserManual_CarInsurance.docx)
> the instructions

It's Okay.

**Comment by densreye** [comment] 2023-01-20 18:08
@pmaldonado-espol , Is everything correct to be able to close the issue?

**Comment by pmaldonado-espol** [comment] 2023-01-20 18:11
> @pmaldonado-espol , Is everything correct to be able to close the issue?

No more chance are needed, thank you.

**Comment by densreye** [comment] 2023-01-20 18:17
@pmaldonado-espol thanks, now I'm going to close the ticket

**Comment by densreye** [comment] 2023-01-20 18:17
The issue is ok, for this reason close the issue

**Closed as completed** 2023-01-20 18:17 UTC
Labels: ﻿﻿﻿Issue assignment, Solve the issue, ﻿﻿﻿Test the solution, ﻿﻿﻿Comoleteness verification, ﻿﻿﻿Enactment of the solution, ﻿﻿﻿﻿Follow up
